// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTAN5dfW17FMfuepo8hyXAxPwyvNoWlbA',
    appId: '1:913767448005:web:fa31d6369d277b68e6dfac',
    messagingSenderId: '913767448005',
    projectId: 'test4-6a850',
    authDomain: 'test4-6a850.firebaseapp.com',
    storageBucket: 'test4-6a850.appspot.com',
    measurementId: 'G-6G8Y5MMCPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKvs5s4ZNGib7JRONiSeQuvXcMzRChocU',
    appId: '1:913767448005:android:872db26a4367bb47e6dfac',
    messagingSenderId: '913767448005',
    projectId: 'test4-6a850',
    storageBucket: 'test4-6a850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLC7QICzt4daCTRLmOaJ1StIO5mJ0ruKg',
    appId: '1:913767448005:ios:586518047dd8a7cae6dfac',
    messagingSenderId: '913767448005',
    projectId: 'test4-6a850',
    storageBucket: 'test4-6a850.appspot.com',
    iosBundleId: 'com.example.test4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLC7QICzt4daCTRLmOaJ1StIO5mJ0ruKg',
    appId: '1:913767448005:ios:6794518f13cb9bf9e6dfac',
    messagingSenderId: '913767448005',
    projectId: 'test4-6a850',
    storageBucket: 'test4-6a850.appspot.com',
    iosBundleId: 'com.example.test4.RunnerTests',
  );
}
